O/feature/deref
thegangtechnology/exco pull request #41
Opened 2020-11-14 17:37 UTC by narongdejsrn

2020-11-14 17:52 UTC, piti118 commented
what does it do in this case <<A<<B1>>>>

2020-11-14 17:55 UTC, piti118 commented
I think there are two kinds of deref then.
1) Template building time deref and
2) Processing time deref.

The second one is a bit dangerous since it gives you a dynamic structure. But I can see some use there.

What I was aiming for was 1) Template building time deref. So we should make another issue one for template building time deref.

2020-11-14 18:14 UTC, piti118 requested changes
Shouldn't be written like this a' This requires you to add this function to every new locator, parser making it a leaky abstraction.

This step should be a post processing for spec before putting it making an ExcelProcessor.
Eg.
```
def process(wb)
    derefed_spec = spec.deref_everything(wb)
    processor = ExcelProcessor.from_spec(derefed_spec)
    ...
```

2020-11-15 05:12 UTC, narongdejsrn commented
> what does it do in this case `<<A<<B1>>>>`
> 
> The question is should it be done recursively??? Can't think of a good use case for now though.
> 
> There is also a danger of infinite loop like if A1 contains text like `<<A1>>`.
> 
> So I think deref once strategy is good for now.

Wouldn't work, only deref once (covered by test)

> Shouldn't be written like this a' This requires you to add this function to every new locator, parser making it a leaky abstraction.
> 
> This step should be a post processing for spec before putting it making an ExcelProcessor.
> Eg.
> 
> ```
> def process(wb)
>     derefed_spec = spec.deref_everything(wb)
>     processor = ExcelProcessor.from_spec(derefed_spec)
>     ...
> ```

Fixed, and now you can turn deref off for specific block by using `deref: no`

2020-11-15 07:25 UTC, piti118 reviewed
I'll do it myself dee gwa this design isn't extensible a'.

2020-11-15 07:25 UTC, piti118 commented on src/exco/extractor/cell_extraction_task.py
> +        if self.deref:
mutating state here is a bad idea. The object can't be reused predictably a' and even worse in multithreaded environment.

2020-11-15 07:25 UTC, piti118 commented on src/exco/extractor/deref/built_in/everything_deref.py
> +        if hasattr(cell_extraction_task.locator, 'label'):
this is also a bad idea the deref shouldn't be fixed to ```label``` and such

2020-12-02 20:16 UTC, closed without merging